name: gh-deploy

on:
  push:
    branches: [ gh-deploy ] # Dispara el flujo de trabajo cuando se hace push a la rama principal (ajusta si es diferente)
  pull_request:
    branches: [ gh-deploy ] # También se ejecuta en pull requests contra la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build --config-file mkdocs.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # La carpeta donde MkDocs genera el sitio estático
          force_orphan: true # Opcional: fuerza la creación de una rama 'gh-pages' independiente