name: Deploy_MkDocs

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Cambia la versión según sea necesario

    - name: Install MkDocs and dependencies
      run: |
        pip install mkdocs mkdocs-material  # Instala MkDocs y el tema Material

    - name: Build the site
      run: mkdocs build --config-file mkdocs.yml # Genera el sitio estático

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # Directorio donde MkDocs genera los archivos